version: '0.0.1'

services:
  app:
    image: '96d4df82c9fc0f99178cc56932c6420597e040b2d04e70f0fa545021b125afb4'
    container_name: app
    expose:
      - '8080'
    ports:
      - '8080:8080'
    environment:
      - DB_USER=kimocha
      - DB_PASSWORD=12345
      - DB_URL=jdbc:postgresql://db:5432/postgres
    depends_on:
      - db
  db:
    image: 'postgres'
    container_name: db
    expose:
      - '5432'
    environment:
      - POSTGRES_USER=kimocha
      - POSTGRES_PASSWORD=12345